name: LMK-AGENT002-MD 
services:
  - name: LMK-AGENTOO2-MD-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
